### ISSUE TITLE
AttributeError: 'RobertaModel' object has no attribute 'output_layer'

### ISSUE THREAD

**Issue by virgulvirgul** [thammegowda/junkdetect#1]
I got an error below:

`AttributeError: 'RobertaModel' object has no attribute 'output_layer'`

Python 3.7
Torch 1.5

**Comment by thammegowda** [comment]
`RobertaModel` has `output_layer` https://github.com/pytorch/fairseq/blob/fad3cf0769843e767155f4d0af18a61b9a804f59/fairseq/models/roberta/model.py#L350 

Could you please post a full stack trace?

Also, which version of fairseq are you using ?   `pip list | grep fairseq` will show it.

FYI, I tested this system on  `fairseq==0.9.0`

**Comment by virgulvirgul** [comment]
fairseq==0.9.0

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/junkdetect", line 8, in <module>
    sys.exit(perplex.main())
  File "/home/ubuntu/.local/lib/python3.7/site-packages/junkdetect/perplex.py", line 52, in main
    score = lm.force_decode(sentence)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/junkdetect/perplex.py", line 29, in force_decode
    scores = self.model.model.output_layers(feats)  # [B=1 x T x V]
  File "/home/ubuntu/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'RobertaModel' object has no attribute 'output_layers'
```

**Comment by thammegowda** [comment]
Thanks,

I will investigate and update this.  
looks like `RobertaModel` itself doesn't have `output_layers` but `RobertaEncoder` does,
and I am not sure how it worked when I tested last time.

**Comment by thammegowda** [comment]
@virgulvirgul 

The file I had in my local cache worked fine, but when I cleared my local cache of torch hub, I got this issue. 
I fixed it and also released to PyPi. 

Please try `pip install junkdetect==0.1.2` and let me know
